tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "itchyny/tap"

brew "anyenv"
brew "aws-shell"
brew "awscli"
brew "bat"
brew "direnv"
brew "exa"
brew "fd"
brew "fzf"
brew "ghq"
brew "git"
brew "gnupg"
brew "go"
brew "haskell-stack"
brew "htop"
brew "jq"
brew "mas"
brew "neovim"
brew "pinentry-mac"
brew "pyenv-virtualenv"
brew "python"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "vim"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "aws/tap/aws-sam-cli"
brew "itchyny/tap/mmv"

cask "1password"
cask "alacritty"
cask "alfred"
cask "bartender"
cask "blackhole"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "google-japanese-ime"
cask "inkdrop"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "obs"
cask "spotify"
cask "visual-studio-code"

mas "LadioCast", id: 411213048
mas "Magnet", id: 441258766
