tap "coderabbitai/tap"
tap "shuymn/tap"
tap "songmu/tap"
tap "xdevplatform/tap"

brew "coderabbitai/tap/git-gtr"
brew "shuymn/tap/kastty"
brew "shuymn/tap/pommitlint"
brew "songmu/tap/maltmill"

cask "1password-cli"
cask "appcleaner"
cask "choosy"
cask "codex"
cask "ghostty"
cask "hammerspoon"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "linearmouse"
cask "orbstack"
cask "raycast"
cask "ukelele"
cask "visual-studio-code"
cask "xdevplatform/tap/xurl"
cask "zed"
