[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_map_keys = v:false
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = v:true
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  source $XDG_CONFIG_HOME/nvim/rc/plugins/onedark.rc.vim

  let g:onedark_terminal_italics = v:true
  colorscheme onedark
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'onedark' }
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = v:true
  let g:indent_guides_auto_colors = v:false

  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=237
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=239
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
hook_add = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/coc.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'
