#!/usr/bin/env sh

# layout
yabai -m config layout bsp
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off

# mouse
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# appearance
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 6
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config window_animation_duration 0.0
yabai -m config active_window_border_color 0xFF94E2D5
yabai -m config normal_window_border_color 0xFF45475A
yabai -m config insert_feedback_color 0xFFF38BA8
yabai -m config external_bar all:0:0

# rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Fig$" manage=off border=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^choose$" manage=off border=off layer=above
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^1Password$" manage=off border=off

echo "yabai configuration loaded.."
