[opener]
edit = [
	{ run = '$EDITOR %s', block = true, for = "unix" },
]

[plugin]
prepend_fetchers = [
	{ id = "git", url = "*", run = "git", group = "git" },
	{ id = "git", url = "*/", run = "git", group = "git" },
]
