auto_sync = false
update_check = false
filter_mode = "workspace"
workspaces = true
style = "full"
inline_height = 30
show_preview = true
max_preview_height = 4
invert = true
show_tabs = false
command_chaining = true
enter_accept = false
secrets_filter = true
search_mode = "fuzzy"
show_numeric_shortcuts = false
history_filter = [
    "^cd$",
    "^ls( |$)",
    "^pwd$",
    "^clear$",
    "^history( |$)",
    "^atuin( |$)",
]
cwd_filter = [
    "/\\.Trash",
    "/tmp",
    "/var/folders",
]
keymap_mode = "vim-insert"

[keymap_cursor]
emacs = "blink-underline"
vim_insert = "blink-bar"
vim_normal = "blink-block"

[ui]
columns = ["exit", "duration", "time", "command"]

[keys]
scroll_exits = false
