[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {'colorscheme': 'onedark'}
'''

# colorscheme
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  if (empty($TMUX) && has("termguicolors"))
    set termguicolors
  endif

	colorscheme onedark
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
