name: Run Renovate

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Create Renovate app token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RENOVATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: dotfiles
          permission-checks: write
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          permission-statuses: write
          permission-vulnerability-alerts: read
          permission-workflows: write

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: .github/renovate-self-hosted.json
          renovate-version: 43.212.4
          token: ${{ steps.app-token.outputs.token }}
